# Generated by Django 4.2.3 on 2023-07-07 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "idCategoria",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Id de categoría",
                    ),
                ),
                (
                    "nombreCategoria",
                    models.CharField(
                        max_length=80, verbose_name="Nombre de la categoría"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "idUsuario",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Id de usuario"
                    ),
                ),
                (
                    "nombreUsuario",
                    models.CharField(max_length=80, verbose_name="nombre de usuario"),
                ),
                (
                    "mail",
                    models.CharField(max_length=80, verbose_name="correo electrónico"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "idProducto",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Id de producto"
                    ),
                ),
                (
                    "nombreProducto",
                    models.CharField(max_length=80, verbose_name="nombre del producto"),
                ),
                (
                    "precioProducto",
                    models.IntegerField(verbose_name="Precio del producto"),
                ),
                (
                    "descripcionProducto",
                    models.CharField(
                        max_length=200, verbose_name="Descripción del producto"
                    ),
                ),
                (
                    "stockProducto",
                    models.IntegerField(verbose_name="Stock del Producto"),
                ),
                (
                    "imagenProducto",
                    models.ImageField(
                        default="sinfoto.jpg",
                        upload_to="images/",
                        verbose_name="Imagen del Producto",
                    ),
                ),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.categoria",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "idCompra",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="Id de compra"
                    ),
                ),
                ("estado", models.IntegerField(verbose_name="Estado de compra")),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="core.usuario",
                    ),
                ),
            ],
        ),
    ]
